examples/ctrlport-demo.rs
examples/soapy.rs
examples/vect.rs
examples/vulkan.rs
examples/websocket.rs
tests/runtime.rs
tests/vulkan.rs

Fix some pedantic options for clippy lints
No issues with code, just ran padantic clippy over the project to get to understand the code a bit better.
Cool project, excited to play around with this!

Add pedantic clippy lints

---

src/blocks/file_sink.rs
src/blocks/file_source.rs

This change adds a `T` parameter to `FileSinkBuilder` and `FileSourceBuilder` to set the item size for the built objects. Additionally, this PR modifies the blocks to support item sizes other than 1. For the most part, the only change needed to support that was properly dividing by the item size when advancing the streams - although the blocks access the streams as slices of `u8`, the streams are internally aware of the item size.
Additionally, for `FileSource`, this PR makes the source silently finish when it received EOF, rather than panic. `read_exact` doesn't tell us how many bytes are read, so we are forced to drop whatever bytes were read and finish the stream. (conceivably, we could rewrite the algorithm to use `read` directly, but one step at a time)

Support multi-byte items in FileSink and FileSource

---

Cargo.toml
src/blocks/mod.rs
src/blocks/wav.rs

Introduce a new Sink so as to create Wav file.
Underlying crate used is [hound](https://github.com/ruuda/hound).
It has been tested in my [CW Discord Bot](https://github.com/loic-fejoz/cw-discord-bot) project.

WavSink Block

---

examples/cw/src/lib.rs

Hopefully this isn't too small of a contribution for my first PR :)
Next step, I'd be interested in writing a CW decoding flow.

Add CW punctuation characters

---

examples/zigbee/src/bin/rx.rs
examples/zigbee/src/bin/tx.rs
examples/zigbee/src/iq_delay.rs

added parameters for the zigbee rx and tx examples and added a udp sink for the rx example similar to the rx wlan example

zigbee improvements

---

src/blocks/soapy_snk.rs
src/blocks/soapy_src.rs

soapy: make new() params options

---

pmt/src/lib.rs

Limited HashMap to String keys since the Hash trait on all Pmt types would be a burden (esp PmtAny).

pmt: add VecPmt and MapStrPmt

---

src/blocks/soapy/sink.rs
src/blocks/soapy/source.rs

Exposed by lint on #95 , thanks Clippy!

soapy: SOAPY_INIT.lock() not awaiting

---

examples/wlan/src/delay.rs
src/blocks/copy.rs
src/blocks/copy_rand.rs
src/blocks/head.rs
src/blocks/throttle.rs
tests/bad_block.rs

Use types in IO slice_unchecked to avoid manual type size computation. Also add Copy trait bound to block type.

unsafe: copy_nonoverlapping -> copy_from_slice

---

crates/futuredsp/src/fir.rs
crates/futuredsp/src/firdes.rs

Fix assertion for cutoff of filter.
Add more generic implementation of taps so as to handle Complex32 IQ stream with Complex32 taps.

fix(futuredsp): FIR assertions and types

---

README.md

Links fixed according to the issue #126

Fixed links in the README file

---

src/blocks/channel_sink.rs
src/blocks/mod.rs

Adds a ChannelSink Block (futures_channel::mpsc)

Add ChannelSink

---

src/blocks/fft.rs

Adding an `fft_size` MessageIO block to the FFT block. This allows for the FFT size to be changed during runtime.

Add FFT Size MessageIO to FFT Block

---

crates/macros/src/lib.rs
src/blocks/message_annotator.rs
src/blocks/message_copy.rs
src/blocks/message_pipe.rs
tests/message_handler.rs

Updated `message_handler` macro to emit fully qualified Result type in return.

---

src/blocks/websocket_pmt_sink.rs

Added support for:
* `Pmt::Blob`
* `Pmt::VecF32` 
* `Pmt::VecU64` 
* `Pmt::String`
I think this covers all the non-scalar variants. Can add the scalar ones if a decision is made on how they should be encoded.

Added more supported `Pmt` variants to `WebsocketPmtSink`

---

src/runtime/tag.rs
tests/tag.rs

Helps with filtering tags relevant for a particular `Kernel`.

Added convenience to `TagAny` for testing against erased type.

---

Cargo.toml
build.rs
check.sh
crates/prophecy/Cargo.toml
crates/types/src/pmt.rs
src/blocks/mod.rs
src/runtime/mod.rs

Also tweaked `check.sh` and `lttng` features to support other development environments. Can split out in a separate PR if that's annoying.

Added support for getting the PmtKind from Pmt.

---

crates/types/src/pmt.rs

Adds `take<T: PmtAny>(self: Box<Self>) -> Option<Box<T>>`

---

crates/prophecy/src/waterfall.rs
examples/spectrum/src/wasm/frontend.rs
examples/spectrum/src/wasm/web.rs
examples/zigbee/src/frontend.rs
src/runtime/logging_wasm.rs

Fix multiple initialization prompts on repeated 'start' clicks in examples/cw

Fix multiple initialization prompts on repeated 'start' clicks in examples/cw

---

crates/futuredsp/build.rs
crates/futuredsp/src/decimating_fir.rs
crates/futuredsp/src/fir.rs
crates/futuredsp/src/lib.rs
crates/macros/src/lib.rs
crates/prophecy/src/main.rs
examples/spectrum/src/wasm/frontend.rs
examples/spectrum/src/wasm/web.rs

build: change stable-nightly detection logic

---

.gitignore
Cargo.toml

- Update seify dependency from 0.16 to 0.17 in Cargo.toml
- Add '.vscode' directory to .gitignore

build(deps): update seify to 0.17 and clean up .gitignore
