src/runtime/buffer/circular.rs
src/runtime/buffer/double_mapped_temp_file.rs
src/runtime/stream_io.rs

Change casts that don't change mut to `.cast<T>()`.

clippy: ptr_as_ptr

---

Cargo.toml

On MacOS I was having issues getting a clean (or any) full compile because of an issue pulling in libclang.  See Issue #16 for more information on this issue.  Based on a suggestion from the author of the `soapysdr` crate, I have bumped the version number to 0.3.1 to correcte the issue.  I have now been able to get clean compile out of the FutureSDR crate.
Change the required version in the `Cargo.toml` file for the `soapysdr` create from 0.3.0 to 0.3.1

Bump the version for `soapysdr` to 0.3.1

---

src/runtime/buffer/double_mapped_temp_file.rs

Close #20
Cannot compile under Raspberry Pi.
Use libc typedef so as to be cross platform.
`cargo test` does not reveal any troubles.

fix(runtime): compilation error re libc

---

src/runtime/buffer/slab.rs

```
fixup! refactor slab buffer
`_ = ...` is a "destructuring assignment", which as of 1.58.1 is behind a
feature flag. However, in nightly it is stabilized, and so this code works
on nightly, but not on stable.
This commit changes the `_ = ...` to `let _ = ...`, which I think has the
same behaviour.
```

Remove destructuring assignment in slab allocator

---

Cargo.toml
futuredsp/Cargo.toml
futuredsp/benches/benchmarks.rs
futuredsp/build.rs
futuredsp/src/fir.rs
futuredsp/src/lib.rs
src/blocks/fir.rs

This PR is a follow-on to #33 (and this contains the same commits as that PR, because I couldn't figure out how to make a PR to merge this into that). But, it's conceptually different so I probably not worth combining the PRs.
So I think we can move the finish condition into the FIR filters by calculating how many more samples we _could_ have produced. If the input is finished, and the core could not have produced more samples (even if it had room), then I think we can finish the block?
If so, this'll make resampling filters work a bit easier, eventually.

Change how FIR filters detect the end condition

---

futuredsp/benches/benchmarks.rs
futuredsp/src/fir.rs
futuredsp/src/lib.rs

This PR is changing the fir in futuredsp to no_std.
The motivation is to keep this crate as platform independent as possible, especially also ready for bare metal programming. More infos about it here: https://docs.rust-embedded.org/book/intro/no-std.html

Consider no_std in futuredsp

---

src/blocks/soapy_src.rs

Just a little change I found while going through the docs

Accept Into<String> for SoapySourceBuilder filter

---

Cargo.toml
src/blocks/apply.rs
src/blocks/combine.rs
src/blocks/fft.rs
src/blocks/file_sink.rs
src/blocks/file_source.rs
src/blocks/filter.rs
src/blocks/fir.rs
src/blocks/head.rs
src/blocks/message_source.rs
src/blocks/mod.rs
src/blocks/null_sink.rs
src/blocks/null_source.rs
src/blocks/soapy_src.rs
src/blocks/source.rs
src/blocks/throttle.rs
src/lib.rs

Inspired by the [nom docs](https://github.com/Geal/nom/blob/main/doc/choosing_a_combinator.md), I started writing some block docs. I've only written a few so far, but I think it's a reasonable cross-section of blocks (and I plan to write more later but I have to go get food right now).
The high points:
* There's a summary table in `futuredsp::blocks` that looks quite nice, and gives a brief description of all the available blocks, as well as sorting them by type.
* Note that the major difference between this and the block listing below is twofold: One, it groups the blocks, and two, it excludes things that aren't blocks, like `MessageSourceBuilder` vs. `MessageSource`. But at the same time, it does duplicate quite a bit of information.
* Each block's docs has a standardized:
* …

Add some docs!

---

futuredsp/benches/benchmarks.rs
futuredsp/src/fir.rs
futuredsp/src/iir.rs
futuredsp/src/kernel.rs
futuredsp/src/lib.rs
futuredsp/src/tapsaccessor.rs
src/blocks/fir.rs
src/blocks/iir.rs
src/blocks/mod.rs

This refactors some of the `futuredsp` code to make the kernel interfaces generic, and adds a IIR filter block.
It isn't currently optimized (at all), and it also only supports `f32` samples with `f32` taps. But, on my mid-tier laptop, it does apparently run at >70MS/s with 7 feedback taps and 1 feedforward tap, which is pretty reasonable, and certainly good enough for e.g. a FM radio de-emphasis filter or other audio work.

Add IIR filter

---

Cargo.toml
examples/firdes/Cargo.toml
examples/firdes/src/main.rs
futuredsp/src/firdes.rs
futuredsp/src/lib.rs
futuredsp/src/math/consts.rs
futuredsp/src/math/mod.rs
futuredsp/src/math/special_funs.rs
futuredsp/src/windows.rs

This implements basic window-based methods for designing FIR lowpass, highpass and bandpass filters.
The functionality is contained in the following modules:
- `futuredsp::windows`: Contains a generic `FilterWindow` trait and a number of commonly used window functions.
- `futuredsp::firdes`: Contains general lowpass, highpass, and bandpass filter design methods based on the window method.
- `futuredsp::firdes::kaiser`: Contains methods for generating lowpass, highpass, and bandpass filters by specifying cutoff frequencies, transition bandwidths, and maximum ripple. The design is based on the Kaiser method.
- `futuredsp::math::consts`: Replacement for `std::f32::consts` and `std::f64::consts`. So far only used for pi.
- `futuredsp::math::special_funs`: Special functions. So far includes an …

Basic FIR design functionality

---

examples/firdes/src/main.rs
futuredsp/Cargo.toml
futuredsp/src/firdes.rs
futuredsp/src/lib.rs
futuredsp/src/math/special_funs.rs
futuredsp/src/windows.rs

This includes a few proposed changes to `firdes` and related modules:
- Window functions no longer use the `FilterWindow` trait, but directly returns the window as `Vec<f64>`. The use of `FilterWindow` trait seemed unnecessary, added a tight dependency between modules, and complicated the use of e.g., simd.
- Several of the window functions now includes a `periodic` argument that specifies whether the window should be constructed to be periodic. This is useful for spectral analysis (e.g., used in radar).
-  `firdes` now supports generic numeric types using the `num_traits::FromPrimitive` trait. This includes of course `f32` and `f64`, but can also be used for e.g., fixed-point numbers. Basically, everything is computed with `f64`, and then converted to the desired type before returning …

Firdes refactoring

---

futuredsp/src/fir.rs

The current FIR filter implementation does not reverse the filter taps before performing the convolution, leading to a correlation operation rather than convolution. This pull request fixes the problem.
For instance, passing a signal `[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]` through a filter with impulse response `[1.0, 2.0]` should produce `[4.0, 7.0, 10.0, 13.0, 16.0]`, but the current implementation produces `[5.0, 8.0, 11.0, 14.0, 17.0]`.
It can be verified with the following example:
```rust
use futuresdr::anyhow::{Context, Result};
use futuresdr::blocks::FirBuilder;
use futuresdr::blocks::VectorSink;
use futuresdr::blocks::VectorSinkBuilder;
use futuresdr::blocks::VectorSourceBuilder;
use futuresdr::runtime::Flowgraph;
use futuresdr::runtime::Runtime;
fn main() -> Result<()> {
let mut fg = …
```

Fix fir filter convolution

---

Cargo.toml
examples/firdes/src/main.rs
examples/fm-receiver/Cargo.toml
examples/fm-receiver/src/main.rs
futuredsp/src/fir.rs
futuredsp/src/firdes.rs
src/blocks/fir.rs
src/blocks/mod.rs

This pull request adds a polyphase implementation of a FIR rational resampler.
Specifically, it adds a `PolyphaseResamplingFirKernel` to `futuredsp::fir`, which implements a simple, stateless polyphase interpolator/decimator.
The following function in `futuredsp::firdes::kaiser` is provided to design Nyquist interpolation/decimation filters (similar to `designMultirateFIR` in Matlab):
```rust
pub fn multirate<T: FromPrimitive>(
interp: usize,
decim: usize,
half_polyphase_len: usize,
max_ripple: f64,
) -> Vec<T>
```
In addition, two functions are provided in `futuresdr::blocks::FirBuilder` to construct resampling blocks:
```rust
pub fn new_resampling<SampleType>(interp: usize, decim: usize) -> Block
```
which creates a interpolation/decimation filter using some standard parameters, and …

Add polyphase rational resampler

---

.github/workflows/ci.yml

Hi,
this PR adds clippy lints for the WASM parts of the project to the CI workflow (partly addressing https://github.com/FutureSDR/FutureSDR/issues/56). 
I'm not sure what features should be enabled for the `Run cargo clippy for wasm32-unknown-unknown (main)` job.

ci: add clippy lints for `wasm32-unknown-unknown` target

---

src/blocks/audio/audio_sink.rs
src/blocks/audio/audio_source.rs
src/blocks/fir.rs
src/blocks/iir.rs
src/blocks/soapy/mod.rs
src/runtime/buffer/circular.rs
src/runtime/buffer/slab.rs
src/runtime/buffer/vulkan/d2h.rs
src/runtime/buffer/vulkan/h2d.rs
src/runtime/buffer/wgpu/d2h.rs
src/runtime/buffer/wgpu/h2d.rs
src/runtime/buffer/zynq/d2h.rs
src/runtime/buffer/zynq/h2d.rs
src/runtime/scheduler/flow.rs
src/runtime/stream_io.rs

Figured it is better to let the compiler infer the traits when possible rather than forcing/faking it.

unsafe: rm unneeded Send/Sync impls

---

src/blocks/tag_debug.rs

The current `TagDebug` block violates the following assert when the input type is different from `u8`: https://github.com/FutureSDR/FutureSDR/blob/main/src/runtime/stream_io.rs#L79.
I believe the implementation is supposed to be like the one implemented in this pull request.
I also created a simple `TagDebug` example, but I did not include it in the pull request (https://github.com/AndersKaloer/FutureSDR/tree/tag-debug-example). The example fails with the current `TagDebug` implementation, but works with this fix.

Fix tag debug

---

examples/debug/Cargo.toml
examples/debug/tag_debug.rs

As suggested in #100, this adds a simple example with the TagDebug block to `examples/debug`.

Add simple example with TagDebug

---

examples/adsb/Cargo.toml
examples/adsb/Gulpfile.js
examples/adsb/README.md
examples/adsb/assets/static/index.html
examples/adsb/assets/static/leaflet.rotatedMarker.js
examples/adsb/assets/static/script.js
examples/adsb/config.toml
examples/adsb/package.json
examples/adsb/serve.py
examples/adsb/src/bin/listen_adsb.rs
examples/adsb/src/decoder.rs
examples/adsb/src/demodulator.rs
examples/adsb/src/lib.rs
examples/adsb/src/preamble_detector.rs
examples/adsb/src/tracker.rs

I implemented an ADS-B decoder with FutureSDR, and thought it could be nice to include as an example.
It also contains a simple web-based map that uses the ctrl_port to interact with the flowgraph.
It relies on [adsb_deku](https://github.com/rsadsb/adsb_deku) for decoding the packets. While it supports a lot of formats, I have only implemented the most common ones, and the ones that were easiest to integrate.
I have not performed any actual comparison to other ADS-B implementations, but it seems to perform quite well on my recordings and with an RTL-SDR with the stock telescopic antenna.
Considering that many people are likely to use this example (along with the others) as an example of how to implement a decoder with FutureSDR, I think it should be as close as possible to "idiomatic" …

ADS-B decoder example

---

examples/README.md
examples/fm-receiver/README.md

Since there are already many different cool examples, it makes quite difficult for new users to figure out what they all do.
Not all examples have documentation in the code and some require extra setup (i.e. going to the folder and executing `cargo run` does not work) or have some other constraints.
This PR should serve as a starting point for giving an overview of the examples and adding some "how-to" for each example.
It's probably best if the authors of the examples add some info themselves. I am only somewhat familiar with the fm-receiver, so I took that as a start.

Add documentation for examples

---

src/blocks/file_source.rs

Fix "For complex samples, the real component must come before the ~~complex~~ _imaginary_ component."

Fix wording in file_source.rs

---

src/runtime/logging_android.rs

The android_logger crate marked the with_min_level method deprecated in version in 0.12.0 and removed it in 0.13.0. Because futuresdr is currently using "0.13" of the crate, this breaks the Android build with "no method named with_min_level` found". Also see
https://github.com/rust-mobile/android_logger-rs/pull/62
This replaces the method call with the new "with_max_level".

Replace removed with_min_level method in android_logger

---

examples/wasm/.cargo/config.toml
examples/wasm/Makefile

Close #133 by adding compiler flags

Fix wasm example

---

Cargo.toml
src/blocks/message_source.rs

In wasm you cannot use `std::time::Instant` so their uses have to be replaced. I hopefully caught all cases where it might be used from a wasm context.

Fix use of `std::time::Instant` in Throttle block

---

crates/futuredsp/src/iir.rs

Updating `memory` in ascending order would set all the elements to `memory[0]`. Fix it.

futuredsp: fix iir memory update

---

examples/wlan/src/bin/loopback.rs
examples/wlan/src/bin/rx.rs
examples/wlan/src/bin/rx_udp.rs
examples/wlan/src/bin/tx.rs
examples/wlan/src/lib.rs
examples/wlan/tests/prefix-vs-tags.rs
src/runtime/mod.rs
src/runtime/tag.rs

Useful in user code to have this as a canonical means of transferring tags.

Lifted `fft_tag_propagation` to `copy_tag_propagation` public API.

---

src/runtime/scheduler/cpu_pin.rs
src/runtime/scheduler/mod.rs

This adds a new scheduler that takes a HashMap that indicates to which CPU each block should be pinned.
---
Background: To do some benchmarking, I wanted to have a scheduler in which I could specify manually in which CPU each block should run, similarly to using `set_processor_affinity()` in GNU Radio (this is one of the things I want to compare with in my benchmarks). I have implemented this as a variant of the `FlowScheduler` that takes a `HashMap` defining in which worker each block should go. The reason why I've implemented this custom scheduler in the `futuresdr` crate is because it doesn't seem possible to implement schedulers in an external crate (for instance, `topology.blocks` is private). So now that I have this written, I was wondering if it made sense to contribute this …

Add CPU pin scheduler

---

src/blocks/seify/source.rs

Also exposes direct construction without builder.
This enables advanced use cases where further manipulation of the `TypedBlock` configuration is desired (e.g. manipulate `MessageInput`s).

Added ability to construct `futuresdr::blocks::seify::Source` as a `TypedBlock`

---

src/runtime/block.rs
src/runtime/mod.rs
src/runtime/topology.rs
tests/connect_error.rs

Update to provide more human-friendly error messages on invalid port specifications:
| Context | Before | After |
|--------|--------|--------|
| Stream | `Block 2 does not have stream port (Name("inner"))` | `Block 'Source' does not have stream port 'inner'` |
| Message | `Block Some(5) does not have message port (Name("out2"))`  | `Block 'MessageSource' does not have message port 'out2'` |

Improved error reporting when a port is mis-specified on a `Block`.

---

src/blocks/seify/config.rs
src/blocks/seify/sink.rs
src/blocks/seify/source.rs
tests/seify.rs

The purpose of this PR is to provide the ability to send a message to the `seify::{Source|Sink}` blocks and get a `Config` with the currently active configuration settings. This is useful for remote operation where it may be important to represent the current settings in a user interface or other coordinating software.

Added ability to query current Source/Sink config via message.

---

src/blocks/message_apply.rs
src/blocks/mod.rs

This pull request introduces a new block called `MessageApply` to the codebase. The `MessageApply` block applies a callback function to incoming messages and emits the result as a new message. The changes include the implementation of the `MessageApply` block, updates to the module documentation, and the addition of the new block to the module exports.
The most important changes are:
* [`src/blocks/message_apply.rs`](diffhunk://#diff-21dcc423d8f6fa15d9d327b0ddddf849398f1c133d5aac48ae909c2511e90901R1-R49): Added the implementation of the `MessageApply` block, which includes the struct definition, constructor, and message handler.
* [`src/blocks/mod.rs`](diffhunk://#diff-8366df386de1191fdc893fda226b6f236cab87656a095ba710372aa1f9c9d6caR51): Updated the documentation to include the …

Added Block to enable message transformation via a provided function.

---

Cargo.toml
examples/custom-routes/Cargo.toml
src/runtime/ctrl_port.rs

This pull request includes updates to dependencies in `Cargo.toml` and improvements to route handling in `src/runtime/ctrl_port.rs`. The most important changes focus on upgrading the `axum` dependency and modifying route definitions for better consistency and maintainability.
Dependency updates:
* Upgraded `axum` from version `0.7` to `0.8` in `Cargo.toml`.
Route handling migrations required for 0.8:
* Changed route parameter syntax from `:param` to `{param}` in `impl ControlPort`.
* Replaced `nest` method with `merge` for combining routes in `impl ControlPort`.

Upgraded Axum to 0.8, migrating breaking changes.
